apiVersion: apps/v1
kind: Deployment
metadata:
  name: reto-epa-reactive-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      role: reto-epa-reactive-logger
  template:
    metadata:
      labels:
        role: reto-epa-reactive-logger
    spec:
      containers:
        - name: reto-epa-reactive-logger
          image: cerjionava/reto_epa_reactive_logger:latest
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: reto-epa-reactive-logger-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    role: reto-epa-reactive-logger
